#baseURL = "https://extremevalue.io"
baseURL = "https://extremevalue.github.io"

languageCode = "en-us"
title = "Training and Digital Education Content at the Next Level"
theme = "navigator-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/logo.png"

# Gestion des langues : FR / EN / NL / DE
#[[Params.listeLangues]]
#code = "fr"
#[[Params.listeLangues]]
#code = "en"

# meta data
author = "ExtremeValue"
description = "Training and Digital Education Content at the Next Level"


############# 2 - Site en ENGLISH
[Languages.en]
weight = 2
languageCode = "en-us"
title = "Training and Digital Education Content at the Next Level"
dateFormat = "January 2, 2006"

home = "Home"
logo = "images/ev-logo-horizontal-white-400.png"
menufixed = false

#footerDescription = "Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
#footerServiceTitle = "Service"
footerQuicklinkTitle = "Quicklinks"
#footerAboutTitle = "ABOOT"
#footerSubscribeTitle = "Subscribe"

# Hero Area Section
[Languages.en.params.hero]
enable  = true
heading = "Training and Digital Education Content at the Next Level"
description = ""
button  = true
btnText = "Learn More"
btnURL  = "/about"
videoThumb = "images/slider/inclusive_front.jpg"
#videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"

# About 2 Section
[Languages.en.params.aboutSm]
enable  = true
title   = "Our mission is to disrupt the edtech space by combining fresh new ideas with leading-edge technology."
description = "There is so much amazing technology available today that can be leveraged to make a difference. Our vision is to harness emerging technology to help those that want to teach, help all those that want to learn.  What makes us different is that we don't focus on singular point solutions, rather we focus on creating end-to-end holistic experiences."

# Blog Section On Homepage
[Languages.en.params.blog]
enable  = false
topTitle= "OUR UNTOLD STORY"
title   = "Blog."
subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
[Languages.en.params.contact]
enable  = false
topTitle= "DROP US A NOTE"
title   = "Contact Us."
subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
address = "14/05, Stockhome <br> Victori Palace , United States"
phone   = "(03) 9283 2617"
fax     = "+61 3827 3590"
facebook= "https://www.facebook.com/"
twitter = "https://twitter.com/"
linkedin= "https://www.linkedin.com/"
dribbble= "https://dribbble.com/"
instagram= "https://www.instagram.com/"
mapLatitude = "51.507351"
mapLongitude= "-0.127758"
mapMarker   = "images/marker.png"

# Call to Action Section on About Page
[Languages.en.params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Join us on our Journey"
subtitle= "."
btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "about"
url     = "about"
weight  = 2
[[menu.nav]]
name    = "contact"
url     = "contact"
weight  = 3
[[menu.nav]]
name    = "contact"
url     = "contact"
weight  = 3
#[[menu.nav]]
#name    = "portfolio"
#url     = "portfolio"
#weight  = 4
#[[menu.nav]]
#name    = "blog"
#url     = "blog"
#weight  = 5

# Footer Service Menu
#[[menu.service]]
#name    = "Contact"
#url     = "contact"
#weight  = 2
#[[menu.service]]
#name    = "about"
#url     = "about"
#weight  = 2
#[[menu.service]]
#name    = "webdevelopment"
#url     = "service"
#weight  = 3

# Footer Quick links Menu
[[menu.quicklink]]
name    = "Contact"
url     = "contact"
weight  = 1
[[menu.quicklink]]
name    = "about"
url     = "about"
weight  = 2
[[menu.quicklink]]
name    = "about"
url     = "about"
weight  = 2
[[menu.quicklink]]
name    = "contact"
url     = "contact"
weight  = 3
#[[menu.quicklink]]
#name    = "badges"
#url     = "about"
#weight  = 4
